### ISSUE TITLE
default custom pop-up styles

### ISSUE THREAD

**Issue by fabrizioanichini** [tcampb/react-calendly#119] opened 2022-05-27 17:58 UTC
Hi!

I'm having some trouble working with the custom button example in the doc. 
This is how is rendered when I click on the button:

<img width="1105" alt="Schermata 2022-05-27 alle 7 55 54 PM" src="https://user-images.githubusercontent.com/34816005/170765121-3d451708-0c14-4d71-b3c3-54b9314aab7d.png">

If I change the component with the InlineComponent everything works fine.

------- Specs ----
MacOs 12.4
Firefox 100.0.2 
Gatsby 4.15.0
react 17.0.1
react-calendly: 4.0.1

**Comment by tcampb** [comment] 2022-05-28 11:35
Hey @fabrizioanichini - 

Do you have a public url / repository you could share where this issue is occurring? When testing the custom button I was unable to recreate the Calendly layout issue:

<img width="1068" alt="image" src="https://user-images.githubusercontent.com/33756113/170823479-1c1db9b3-1511-4a46-a03b-48227f08313e.png">

It looks like this is an issue with Calendly's CSS styles as `react-calendly` cannot change the scheduling page's CSS properties directly.

**Comment by fabrizioanichini** [comment] 2022-05-28 13:04
Hi @tcampb , 
sure you can find the code at https://github.com/MediaWaveCloud/socialwave-static.
I'm trying to migrate the current website to gatsby but calendly dosent seems to work properly. You can find the custom button at the end of the index.js page.

**Comment by fabrizioanichini** [comment] 2022-05-28 13:05
<img width="1411" alt="Schermata 2022-05-28 alle 3 04 49 PM" src="https://user-images.githubusercontent.com/34816005/170826809-2a051c56-b940-4bb3-bd38-5e68f378ef66.png">

For reference, this is how I experience calendly in the current website

**Comment by tcampb** [comment] 2022-05-28 13:47
Thanks for the quick response @fabrizioanichini. 

I ran the code locally and was still unable to reproduce the issue as seen below:

<img width="1211" alt="image" src="https://user-images.githubusercontent.com/33756113/170827926-47a678bd-7156-426c-81d6-4333e38eeade.png">

**Comment by tcampb** [comment] 2022-06-03 18:04
Hey @fabrizioanichini, I'm going to close this issue for now since I'm unable to recreate it locally. If you continue to have the issue after deploying the site to a public url feel free to reopen the issue with the url and I can look into it further.

**Closed by tcampb** 2022-06-03 18:04 UTC
